// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
//import org.junit.After;
//import org.junit.Before;
//import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import static org.openqa.selenium.support.ui.ExpectedConditions.presenceOfElementLocated;

public class FirstTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeMethod
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();

        driver.get("http://localhost:8099/");
        driver.manage().window().setSize(new Dimension(1680, 991));
        driver.findElement(By.linkText("Enter the Store")).click();
    }
    @AfterMethod
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void firstTest() throws InterruptedException {
        WebDriverWait wait = new WebDriverWait(driver, 10);
//        driver.findElement(By.cssSelector("#SidebarContent > a:nth-child(1) > img")).click();
//        By searchInput = By.cssSelector("a[href*='FISH']");
//        wait.until(presenceOfElementLocated(searchInput));
        driver.findElement(By.cssSelector("a[href*='FISH']")).click();
//        driver.findElement(By.linkText("FI-SW-01")).click();
//        driver.findElement(By.linkText("Add to Cart")).click();
////        driver.findElement(By.id("stripes-1415605895")).click();
////        driver.findElement(By.cssSelector("p:nth-child(2)")).click();
//        driver.findElement(By.name("login")).sendKeys("ACID");
//        driver.findElement(By.name("password")).sendKeys("ACID");
////        driver.findElement(By.id("stripes-1415605895")).click();
////        driver.findElement(By.name("password")).click();
//        driver.findElement(By.name("signon")).click();
//        driver.findElement(By.linkText("My Account")).click();
//        driver.findElement(By.linkText("Proceed to Checkout")).click();
    }
}
